[custom]
;不要随意改变关键字，否则会导致出错
;参考acl4SSR规则
;edit by dx

;To get emojis at here
;https://gist.github.com/rxaviers/7360908

;setting guide
;https://www.youtube.com/watch?v=D841V_xgykg&t=6s

;Referece list for chinese applications
;https://github.com/ACL4SSR/ACL4SSR/tree/master/Clash/Ruleset
;https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash
;https://github.com/vernesong/OpenClash/issues/4350

;设置规则标志位
;ruleset=📺 Bilibili PC_Cell Switch,https://raw.githubusercontent.com/deepline1986/clashGoHome/refs/heads/main/bilibili_PcCellSwitch.list
;ruleset=📺 哔哩哔哩HMT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
;ruleset=📺 Bilibili Main,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=📺 Migu,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Migu/Migu.list
ruleset=📺 CCTV,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/CCTV.list
;ruleset=📺 iQIYI,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Iqiyi.list
;ruleset=🎶 QQ & QQ Music,https://raw.githubusercontent.com/deepline1986/clashGoHome/refs/heads/main/qq.list
;ruleset=🎶 NetEase Music,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list

;ruleset=🎯 GEOIPcn,[]GEOIP,CN,no-resolve
ruleset=🐟 Rest,[]FINAL
;设置规则标志位

;设置分组标志位
;custom_proxy_group=📺 Bilibili PC_Cell Switch`select`[]📱 CELL & TABLET`[]💻 LAPTOP & PC
;custom_proxy_group=📺 哔哩哔哩HMT`select`[]DIRECT`[]Proxy
;custom_proxy_group=📺 Bilibili Main`select`[]DIRECT`[]Proxy
custom_proxy_group=📺 Migu`select`[]DIRECT`[]Proxy
custom_proxy_group=📺 CCTV`select`[]DIRECT`[]Proxy
;custom_proxy_group=📺 iQIYI`select`[]DIRECT`[]Proxy
;custom_proxy_group=🎶 QQ & QQ Music`select`[]DIRECT`[]Proxy
;custom_proxy_group=🎶 NetEase Music`select`[]DIRECT`[]Proxy

;custom_proxy_group=🎯 GEOIPcn`select`[]DIRECT`[]Proxy
custom_proxy_group=🐟 Rest`select`[]DIRECT`[]Proxy
;设置分组标志位

;设置分组标志位-节点
custom_proxy_group=Proxy`select`.*
;设置分组标志位-节点

;设置分组标志位-别名
;custom_proxy_group=📱 CELL & TABLET`select`[]DIRECT`[]Proxy
;custom_proxy_group=💻 LAPTOP & PC`select`[]DIRECT`[]Proxy
;设置分组标志位-别名

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck
